/**
 * Characterization of `runHarnessSync` outcomes through the shipped entry
 * point (project-health-audit TASK-777). Pins the report rows and on-disk
 * results of the catalogue grouping and per-group evaluation before refactor.
 */

import {
	chmod,
	lstat,
	mkdir,
	readFile,
	realpath,
	rm,
	writeFile,
} from "node:fs/promises";
import { basename, join, relative } from "node:path";
import { describe, expect, test } from "vitest";
import { resolveHarnessTransactionPaths } from "../../lib/harness-adapters/provenance.ts";
import type {
	HarnessAsset,
	SourceHealthRow,
	SyncRequest,
} from "../../lib/harness-adapters/types.ts";
import {
	type HarnessSyncReport,
	runHarnessSync,
} from "../../lib/skills/exporter.ts";
import { useTempDir } from "../helpers/fs.ts";

const GENERATED_HEADER = "<!-- Generated by cosmonauts; do not edit. -->\n";

const tmp = useTempDir("exporter-sync-characterization-");

interface Fixture {
	readonly projectRoot: string;
	readonly homeRoot: string;
	readonly sourceRoot: string;
	readonly assets: readonly HarnessAsset[];
	readonly sourceHealth: readonly SourceHealthRow[];
	readonly canonicalRoot: string;
}

async function createFixture(names: readonly string[]): Promise<Fixture> {
	const projectRoot = join(tmp.path, "project");
	const homeRoot = join(tmp.path, "home");
	const sourceRoot = join(projectRoot, "src");
	await mkdir(homeRoot, { recursive: true });
	for (const name of names) {
		await mkdir(join(sourceRoot, name), { recursive: true });
		await writeFile(join(sourceRoot, name, "SKILL.md"), `# ${name}\n`);
	}
	return {
		projectRoot,
		homeRoot,
		sourceRoot,
		canonicalRoot: await realpath(tmp.path),
		assets: names.map((name) => ({
			assetId: `skill:${name}`,
			kind: "skill",
			ownership: { kind: "project" },
			sourceRootId: "root:fixture",
			sourceRoot,
			sourcePath: name,
			logicalPath: name,
			outputIdentity: name,
			defaultScope: "project",
		})),
		sourceHealth: [
			{
				sourceRootId: "root:fixture",
				sourceRoot,
				domain: "fixture",
				status: "complete",
				issues: [],
			},
		],
	};
}

function sync(
	fixture: Fixture,
	request: SyncRequest,
	assets: readonly HarnessAsset[] = fixture.assets,
): Promise<HarnessSyncReport> {
	return runHarnessSync({
		projectRoot: fixture.projectRoot,
		homeRoot: fixture.homeRoot,
		assets,
		sourceHealth: fixture.sourceHealth,
		request,
	});
}

const claudeProject = {
	targetIds: ["claude"],
	scopes: ["project"],
	reconciliation: "partial",
} as const satisfies Omit<SyncRequest, "check">;

function summarize(report: HarnessSyncReport, fixture: Fixture) {
	return {
		exitCode: report.exitCode,
		rows: report.rows.map((row) => ({
			asset: row.asset,
			target: row.target,
			scope: row.scope,
			targetPath: relative(fixture.canonicalRoot, row.targetPath),
			before: row.before,
			reason: row.reason,
			action: row.action,
			final: row.final,
			recovery: row.recovery?.state,
		})),
	};
}

async function exists(path: string): Promise<boolean> {
	try {
		await lstat(path);
		return true;
	} catch {
		return false;
	}
}

describe("runHarnessSync check mode", () => {
	test("reports missing targets without writing and exits 1", async () => {
		const fixture = await createFixture(["a", "b"]);

		const report = await sync(fixture, { ...claudeProject, check: true });

		expect(summarize(report, fixture)).toEqual({
			exitCode: 1,
			rows: ["a", "b"].map((name) => ({
				asset: `skill:${name}`,
				target: "claude",
				scope: "project",
				targetPath: `project/.claude/skills/${name}`,
				before: "missing",
				reason: "missing",
				action: "none",
				final: "missing",
				recovery: undefined,
			})),
		});
		await expect(exists(join(fixture.projectRoot, ".claude"))).resolves.toBe(
			false,
		);
	});

	test("reports a changed source as source-ahead without replacing the target", async () => {
		const fixture = await createFixture(["a", "b"]);
		await sync(fixture, { ...claudeProject, check: false });
		await writeFile(join(fixture.sourceRoot, "a", "SKILL.md"), "# a2\n");

		const report = await sync(fixture, { ...claudeProject, check: true });

		expect(
			summarize(report, fixture).rows.map(
				({ asset, before, reason, final }) => [asset, before, reason, final],
			),
		).toEqual([
			["skill:a", "source-ahead", "source-changed", "source-ahead"],
			["skill:b", "current", "current", "current"],
		]);
		expect(report.exitCode).toBe(1);
		expect(
			await readFile(
				join(fixture.projectRoot, ".claude/skills/a/SKILL.md"),
				"utf8",
			),
		).toBe(`${GENERATED_HEADER}# a\n`);
	});

	test("exits 0 when every target is current", async () => {
		const fixture = await createFixture(["a"]);
		await sync(fixture, { ...claudeProject, check: false });

		const report = await sync(fixture, { ...claudeProject, check: true });

		expect(summarize(report, fixture)).toMatchObject({
			exitCode: 0,
			rows: [{ before: "current", action: "none", final: "current" }],
		});
	});

	test("reports a pending journal on every row of the group", async () => {
		const fixture = await createFixture(["a", "b"]);
		await sync(fixture, { ...claudeProject, check: false });
		const ownerRoot = join(fixture.projectRoot, ".claude");
		const { journalPath } = resolveHarnessTransactionPaths(ownerRoot, "claude");
		await writeFile(journalPath, "{}");

		const report = await sync(fixture, { ...claudeProject, check: true });

		expect(summarize(report, fixture)).toMatchObject({
			exitCode: 1,
			rows: [
				{ asset: "skill:a", reason: "pending-journal", final: "source-ahead" },
				{ asset: "skill:b", reason: "pending-journal", final: "source-ahead" },
			],
		});
	});

	test("emits one owner-root recovery row when a pending journal group has no rows", async () => {
		const fixture = await createFixture([]);
		const ownerRoot = join(fixture.projectRoot, ".claude");
		await mkdir(ownerRoot, { recursive: true });
		const { journalPath } = resolveHarnessTransactionPaths(ownerRoot, "claude");
		await writeFile(journalPath, "{}");

		const report = await sync(fixture, {
			...claudeProject,
			reconciliation: "complete",
			check: true,
		});

		expect(summarize(report, fixture)).toEqual({
			exitCode: 1,
			rows: [
				{
					asset: "(owner-root)",
					target: "claude",
					scope: "project",
					targetPath: "project/.claude",
					before: "source-ahead",
					reason: "pending-journal",
					action: "none",
					final: "source-ahead",
					recovery: "pending-journal",
				},
			],
		});
	});

	test("emits an observation-failure row when the manifest cannot be parsed", async () => {
		const fixture = await createFixture(["a"]);
		const ownerRoot = join(fixture.projectRoot, ".claude");
		await mkdir(ownerRoot, { recursive: true });
		await writeFile(
			join(ownerRoot, ".cosmonauts-harness-manifest.json"),
			"nope",
		);

		const report = await sync(fixture, { ...claudeProject, check: true });

		expect(report.exitCode).toBe(1);
		expect(report.rows).toHaveLength(1);
		expect(report.rows[0]).toMatchObject({
			asset: "(owner-root)",
			action: "failed",
			final: "source-ahead",
			recovery: { state: "observation-failure" },
		});
		expect(report.rows[0]?.reason).toMatch(/^observation-failure:/);
	});
});

describe("runHarnessSync write mode", () => {
	test("creates missing targets, then reports current rows as no-ops", async () => {
		const fixture = await createFixture(["a", "b"]);

		const created = await sync(fixture, { ...claudeProject, check: false });

		expect(summarize(created, fixture)).toEqual({
			exitCode: 0,
			rows: ["a", "b"].map((name) => ({
				asset: `skill:${name}`,
				target: "claude",
				scope: "project",
				targetPath: `project/.claude/skills/${name}`,
				before: "missing",
				reason: "missing",
				action: "create",
				final: "current",
				recovery: "none",
			})),
		});
		expect(
			await readFile(
				join(fixture.projectRoot, ".claude/skills/b/SKILL.md"),
				"utf8",
			),
		).toBe(`${GENERATED_HEADER}# b\n`);

		const again = await sync(fixture, { ...claudeProject, check: false });
		expect(summarize(again, fixture)).toMatchObject({
			exitCode: 0,
			rows: [
				{ before: "current", action: "none", final: "current" },
				{ before: "current", action: "none", final: "current" },
			],
		});
	});

	test("replaces a source-ahead target and keeps a locally edited one", async () => {
		const fixture = await createFixture(["a", "b"]);
		await sync(fixture, { ...claudeProject, check: false });
		await writeFile(join(fixture.sourceRoot, "a", "SKILL.md"), "# a2\n");
		await writeFile(
			join(fixture.projectRoot, ".claude/skills/b/SKILL.md"),
			"edited\n",
		);

		const report = await sync(fixture, { ...claudeProject, check: false });

		expect(
			summarize(report, fixture).rows.map(
				({ asset, before, action, final }) => [asset, before, action, final],
			),
		).toEqual([
			["skill:a", "source-ahead", "replace", "current"],
			["skill:b", "locally-edited", "none", "locally-edited"],
		]);
		expect(report.exitCode).toBe(1);
		expect(
			await readFile(
				join(fixture.projectRoot, ".claude/skills/a/SKILL.md"),
				"utf8",
			),
		).toBe(`${GENERATED_HEADER}# a2\n`);
		expect(
			await readFile(
				join(fixture.projectRoot, ".claude/skills/b/SKILL.md"),
				"utf8",
			),
		).toBe("edited\n");
	});

	test("writes both default targets as separate owner groups", async () => {
		const fixture = await createFixture(["a"]);

		const report = await sync(fixture, {
			scopes: ["project"],
			reconciliation: "partial",
			check: false,
		});

		expect(summarize(report, fixture)).toMatchObject({
			exitCode: 0,
			rows: [
				{ target: "claude", targetPath: "project/.claude/skills/a" },
				{ target: "codex", targetPath: "project/.agents/skills/a" },
			],
		});
		await expect(
			exists(join(fixture.projectRoot, ".agents/skills/a/SKILL.md")),
		).resolves.toBe(true);
	});

	test("writes personal scope under the home root", async () => {
		const fixture = await createFixture(["a"]);

		const report = await sync(fixture, {
			targetIds: ["claude"],
			scopes: ["personal"],
			reconciliation: "partial",
			check: false,
		});

		expect(summarize(report, fixture)).toMatchObject({
			exitCode: 0,
			rows: [{ scope: "personal", targetPath: "home/.claude/skills/a" }],
		});
		await expect(
			exists(join(fixture.homeRoot, ".claude/skills/a/SKILL.md")),
		).resolves.toBe(true);
		await expect(exists(join(fixture.projectRoot, ".claude"))).resolves.toBe(
			false,
		);
	});

	test.skipIf(process.getuid?.() === 0)(
		"reports a failed apply with the restored-old evidence and leaves the target missing",
		async () => {
			const fixture = await createFixture(["w"]);
			const skillsDir = join(fixture.projectRoot, ".claude/skills");
			await mkdir(skillsDir, { recursive: true });
			await chmod(skillsDir, 0o500);
			try {
				const report = await sync(fixture, { ...claudeProject, check: false });

				expect(summarize(report, fixture)).toMatchObject({
					exitCode: 1,
					rows: [{ before: "missing", action: "create", final: "missing" }],
				});
				expect(report.rows[0]?.evidence).toBe("restored-old");
			} finally {
				await chmod(skillsDir, 0o700);
			}
			await expect(exists(join(skillsDir, "w"))).resolves.toBe(false);
		},
	);

	test("reports an ambiguous recovery on each row when the journal is malformed", async () => {
		const fixture = await createFixture(["a", "b"]);
		const ownerRoot = join(fixture.projectRoot, ".claude");
		await mkdir(ownerRoot, { recursive: true });
		const { journalPath } = resolveHarnessTransactionPaths(ownerRoot, "claude");
		await writeFile(journalPath, "{}");

		const report = await sync(fixture, { ...claudeProject, check: false });

		expect(report.exitCode).toBe(1);
		expect(report.rows.map((row) => [row.asset, row.recovery])).toEqual([
			[
				"skill:a",
				{ state: "ambiguous", reason: "Malformed harness owner-root journal." },
			],
			[
				"skill:b",
				{ state: "ambiguous", reason: "Malformed harness owner-root journal." },
			],
		]);
		await expect(exists(join(ownerRoot, "skills"))).resolves.toBe(false);
	});

	test("emits an owner-root recovery row for an ambiguous journal on an empty group", async () => {
		const fixture = await createFixture([]);
		const ownerRoot = join(fixture.projectRoot, ".claude");
		await mkdir(ownerRoot, { recursive: true });
		const { journalPath } = resolveHarnessTransactionPaths(ownerRoot, "claude");
		await writeFile(journalPath, "{}");

		const report = await sync(fixture, {
			...claudeProject,
			reconciliation: "complete",
			check: false,
		});

		expect(report.exitCode).toBe(1);
		expect(report.rows).toHaveLength(1);
		expect(report.rows[0]).toMatchObject({
			asset: "(owner-root)",
			reason: "ambiguous",
			final: "source-ahead",
			recovery: { state: "ambiguous" },
		});
	});

	test("reports lock contention on each row with the holder pid", async () => {
		const fixture = await createFixture(["a"]);
		const ownerRoot = join(fixture.projectRoot, ".claude");
		await mkdir(ownerRoot, { recursive: true });
		const { lockPath } = resolveHarnessTransactionPaths(ownerRoot, "claude");
		await writeFile(
			lockPath,
			`${JSON.stringify({ pid: process.pid, uuid: "held", startedAt: new Date().toISOString() })}\n`,
		);

		const report = await sync(fixture, { ...claudeProject, check: false });

		expect(summarize(report, fixture)).toMatchObject({
			exitCode: 1,
			rows: [{ before: "missing", action: "create", final: "missing" }],
		});
		expect(report.rows[0]?.recovery).toEqual({
			state: "lock-contended",
			detail: `${join(await realpath(fixture.projectRoot), basename(lockPath))} pid=${process.pid}`,
		});
		await expect(exists(join(ownerRoot, "skills"))).resolves.toBe(false);
	}, 15_000);

	test("emits an owner-root lock-contended row for an empty group", async () => {
		const fixture = await createFixture([]);
		const ownerRoot = join(fixture.projectRoot, ".claude");
		await mkdir(ownerRoot, { recursive: true });
		const { lockPath } = resolveHarnessTransactionPaths(ownerRoot, "claude");
		await writeFile(
			lockPath,
			`${JSON.stringify({ pid: process.pid, uuid: "held", startedAt: new Date().toISOString() })}\n`,
		);

		const report = await sync(fixture, {
			...claudeProject,
			reconciliation: "complete",
			check: false,
		});

		expect(report.exitCode).toBe(1);
		expect(report.rows).toHaveLength(1);
		expect(report.rows[0]).toMatchObject({
			asset: "(owner-root)",
			reason: "lock-contended",
			recovery: { state: "lock-contended" },
		});
	}, 15_000);
});

describe("runHarnessSync catalogue grouping", () => {
	test("rejects an unregistered target", async () => {
		const fixture = await createFixture(["a"]);

		await expect(
			sync(fixture, {
				...claudeProject,
				targetIds: ["nope" as never],
				check: true,
			}),
		).rejects.toThrow('Harness target "nope" is not registered.');
	});

	test("rejects a declared but unimplemented target", async () => {
		const fixture = await createFixture(["a"]);

		await expect(
			sync(fixture, {
				...claudeProject,
				targetIds: ["open-code"],
				check: true,
			}),
		).rejects.toThrow(
			'Harness target "open-code" is declared but unimplemented.',
		);
	});

	test("rejects an explicit target that does not support the asset kind", async () => {
		const fixture = await createFixture([]);
		const command = commandAsset(fixture);

		await expect(
			sync(
				fixture,
				{ targetIds: ["codex"], reconciliation: "partial", check: true },
				[command],
			),
		).rejects.toThrow(
			'Harness target "codex" does not support asset kind "command".',
		);
	});

	test("skips targets that do not support the asset kind when targets are omitted", async () => {
		const fixture = await createFixture([]);
		await mkdir(join(fixture.sourceRoot, "cmds"), { recursive: true });
		await writeFile(
			join(fixture.sourceRoot, "cmds", "go.md"),
			"---\ndescription: go\n---\nDo it\n",
		);

		const report = await sync(
			fixture,
			{ reconciliation: "partial", check: true },
			[commandAsset(fixture)],
		);

		expect(
			report.rows.map((row) => [row.asset, row.target, row.final]),
		).toEqual([["command:go", "claude", "missing"]]);
	});

	test("returns no rows when the request selects nothing", async () => {
		const fixture = await createFixture(["a"]);

		const report = await sync(fixture, {
			...claudeProject,
			assetIds: ["skill:other"],
			check: false,
		});

		expect(report).toEqual({ rows: [], exitCode: 0 });
	});

	test("complete reconciliation removes a synced target whose source is gone and keeps an edited one", async () => {
		const fixture = await createFixture(["a", "b"]);
		await sync(fixture, { ...claudeProject, check: false });
		await writeFile(
			join(fixture.projectRoot, ".claude/skills/b/SKILL.md"),
			"edited\n",
		);

		const report = await sync(
			fixture,
			{ ...claudeProject, reconciliation: "complete", check: false },
			[],
		);

		expect(
			summarize(report, fixture).rows.map(
				({ asset, before, reason, action, final }) => [
					asset,
					before,
					reason,
					action,
					final,
				],
			),
		).toEqual([
			[
				"skill:a",
				"source-ahead",
				"source-removed",
				"remove-target-and-entry",
				"current",
			],
			["skill:b", "locally-edited", "source-removed", "none", "locally-edited"],
		]);
		expect(report.exitCode).toBe(1);
		await expect(
			exists(join(fixture.projectRoot, ".claude/skills/a")),
		).resolves.toBe(false);
		await expect(
			exists(join(fixture.projectRoot, ".claude/skills/b/SKILL.md")),
		).resolves.toBe(true);
	});

	test("complete reconciliation in check mode reports only the rows that still need action", async () => {
		const fixture = await createFixture(["a", "b"]);
		await sync(fixture, { ...claudeProject, check: false });
		await writeFile(
			join(fixture.projectRoot, ".claude/skills/b/SKILL.md"),
			"edited\n",
		);
		await sync(fixture, { ...claudeProject, check: false });

		const report = await sync(
			fixture,
			{ ...claudeProject, reconciliation: "complete", check: true },
			[],
		);

		expect(report.exitCode).toBe(1);
		expect(
			report.rows.map((row) => [row.asset, row.reason, row.final]),
		).toEqual([
			["skill:a", "source-removed", "source-ahead"],
			["skill:b", "source-removed", "locally-edited"],
		]);
		await expect(
			exists(join(fixture.projectRoot, ".claude/skills/a/SKILL.md")),
		).resolves.toBe(true);
	});

	test("complete reconciliation that excludes skills does not create an owner group", async () => {
		const fixture = await createFixture(["a"]);
		await sync(fixture, { ...claudeProject, check: false });

		const report = await sync(
			fixture,
			{
				...claudeProject,
				kinds: ["command"],
				reconciliation: "complete",
				check: false,
			},
			[],
		);

		expect(report).toEqual({ rows: [], exitCode: 0 });
		await expect(
			exists(join(fixture.projectRoot, ".claude/skills/a/SKILL.md")),
		).resolves.toBe(true);
	});

	test("forgetting a removed asset spans every default target and scope", async () => {
		const fixture = await createFixture(["a"]);
		await sync(fixture, {
			targetIds: ["claude", "codex"],
			scopes: ["project", "personal"],
			reconciliation: "partial",
			check: false,
		});

		const report = await sync(
			fixture,
			{
				reconciliation: "partial",
				check: false,
				forgetRemovedAssetIds: ["skill:a"],
			},
			[],
		);

		expect(
			summarize(report, fixture).rows.map(
				({ target, scope, reason, action, final }) => [
					target,
					scope,
					reason,
					action,
					final,
				],
			),
		).toEqual([
			["claude", "project", "explicit-forget", "forget-entry", "current"],
			["claude", "personal", "explicit-forget", "forget-entry", "current"],
			["codex", "project", "explicit-forget", "forget-entry", "current"],
			["codex", "personal", "explicit-forget", "forget-entry", "current"],
		]);
		expect(report.exitCode).toBe(0);
		await expect(
			exists(join(fixture.projectRoot, ".claude/skills/a/SKILL.md")),
		).resolves.toBe(true);
	});

	test("forgetting keeps a removed asset's target when the source health is incomplete", async () => {
		const fixture = await createFixture(["a"]);
		await sync(fixture, { ...claudeProject, check: false });
		await rm(join(fixture.sourceRoot, "a"), { recursive: true });

		const report = await runHarnessSync({
			projectRoot: fixture.projectRoot,
			homeRoot: fixture.homeRoot,
			assets: [],
			sourceHealth: [
				{
					...(fixture.sourceHealth[0] as SourceHealthRow),
					status: "incomplete",
					issues: [
						{ kind: "read", path: fixture.sourceRoot, message: "unreadable" },
					],
				},
			],
			request: {
				...claudeProject,
				kinds: ["skill"],
				reconciliation: "complete",
				check: false,
				forgetRemovedAssetIds: ["skill:a"],
			},
		});

		expect(summarize(report, fixture)).toMatchObject({
			exitCode: 1,
			rows: [
				{
					reason: "inventory-incomplete",
					action: "none",
					final: "source-ahead",
				},
			],
		});
	});
});

function commandAsset(fixture: Fixture): HarnessAsset {
	return {
		assetId: "command:go",
		kind: "command",
		ownership: { kind: "project" },
		sourceRootId: "root:fixture",
		sourceRoot: fixture.sourceRoot,
		sourcePath: "cmds/go.md",
		logicalPath: "go",
		outputIdentity: "go",
		defaultScope: "project",
	};
}
