import {
	lstat,
	mkdir,
	readdir,
	readFile,
	realpath,
	rm,
	symlink,
	writeFile,
} from "node:fs/promises";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import type {
	HarnessAuthoredLink,
	HarnessGeneratedNodeProvenance,
} from "./provenance.ts";
import { sha256 } from "./provenance.ts";
import type {
	HarnessAsset,
	HarnessLinkShape,
	ResolvedHarnessAssetTarget,
	SyncMode,
} from "./types.ts";

export const GENERATED_BY_MARKER = Buffer.from(
	"<!-- Generated by cosmonauts; do not edit. -->\n",
);
export const GENERATED_BY_MARKER_VERSION = 1 as const;

export interface GeneratedHarnessNode {
	readonly relativePath: string;
	readonly inputBytes: Uint8Array;
	readonly renderedBytes: Uint8Array;
}

export interface PreparedHarnessMaterialization {
	readonly mode: SyncMode;
	readonly sourceShape: "directory" | "file";
	readonly canonicalSource: string;
	readonly sourceDigest: string;
	readonly renderedDigest: string;
	readonly baselineDigest: string;
	readonly copyNodes: readonly RenderedFileNode[];
	readonly directLinkShape?: "directory" | "flat-skill";
	readonly authoredLinks: readonly HarnessAuthoredLink[];
	readonly generatedNodes: readonly PreparedGeneratedNode[];
}

interface SourceFileNode {
	readonly relativePath: string;
	readonly canonicalSource: string;
	readonly bytes: Buffer;
}

export interface RenderedFileNode {
	readonly relativePath: string;
	readonly bytes: Buffer;
}

interface PreparedGeneratedNode extends HarnessGeneratedNodeProvenance {
	readonly bytes: Buffer;
}

export function renderIdentityMarkdown(source: Uint8Array): Buffer {
	const bytes = Buffer.from(source);
	if (bytes.indexOf(GENERATED_BY_MARKER) !== -1) {
		throw new Error(
			"Identity Markdown source already contains the generated-by marker; refusing to create a duplicate marker.",
		);
	}
	const offset = frontmatterEndOffset(bytes);
	return Buffer.concat([
		bytes.subarray(0, offset),
		GENERATED_BY_MARKER,
		bytes.subarray(offset),
	]);
}

export function stripGeneratedByMarker(rendered: Uint8Array): Buffer {
	const bytes = Buffer.from(rendered);
	const offset = frontmatterEndOffset(bytes);
	if (
		offset === 0 ||
		!bytes
			.subarray(offset, offset + GENERATED_BY_MARKER.length)
			.equals(GENERATED_BY_MARKER)
	) {
		throw new Error(
			"Rendered Markdown does not contain the generated-by marker at the deterministic frontmatter boundary.",
		);
	}
	if (
		bytes.indexOf(GENERATED_BY_MARKER, offset + GENERATED_BY_MARKER.length) !==
		-1
	) {
		throw new Error(
			"Rendered Markdown contains more than one generated-by marker.",
		);
	}
	return Buffer.concat([
		bytes.subarray(0, offset),
		bytes.subarray(offset + GENERATED_BY_MARKER.length),
	]);
}

export function assertClaudeCommandFrontmatter(source: Uint8Array): void {
	const bytes = Buffer.from(source);
	const offset = frontmatterEndOffset(bytes);
	if (offset === 0) {
		throw new Error("Claude command source requires YAML frontmatter.");
	}
	const frontmatter = bytes.subarray(0, offset).toString("utf8");
	if (!/^description:[^\r\n]+$/m.test(frontmatter)) {
		throw new Error("Claude command source requires a non-empty description.");
	}
	if (!/^argument-hint:[^\r\n]+$/m.test(frontmatter)) {
		throw new Error(
			"Claude command source requires a non-empty argument-hint.",
		);
	}
}

export async function prepareHarnessMaterialization(options: {
	readonly projectRoot: string;
	readonly asset: HarnessAsset;
	readonly target: ResolvedHarnessAssetTarget;
	readonly mode: SyncMode;
	readonly generatedNodes?: readonly GeneratedHarnessNode[];
}): Promise<PreparedHarnessMaterialization> {
	validateTargetShape(options.asset, options.target, options.mode);
	const source = await readRegisteredSource(options.projectRoot, options.asset);
	const linkShape = resolveLinkShape(options.asset, source.shape);
	validateLinkShape(options.asset, options.target, options.mode, linkShape);
	const generated = prepareGeneratedNodes(options.generatedNodes ?? []);
	validateGeneratedShape(options.asset, source, generated);

	const generatedPaths = new Set(generated.map((node) => node.relativePath));
	const authored = source.files.filter(
		(node) => !generatedPaths.has(node.relativePath),
	);
	const authoredLinks = authored.map((node) => ({
		relativePath: node.relativePath,
		expectedCanonicalSource: node.canonicalSource,
	}));

	const copyNodes = source.files
		.map((node): RenderedFileNode | undefined => {
			const generatedNode = generated.find(
				(candidate) => candidate.relativePath === node.relativePath,
			);
			if (generatedNode) {
				return {
					relativePath: node.relativePath,
					bytes: generatedNode.bytes,
				};
			}
			return {
				relativePath: node.relativePath,
				bytes: shouldAddMarker(options.asset, source.shape, node.relativePath)
					? renderIdentityMarkdown(node.bytes)
					: node.bytes,
			};
		})
		.filter((node): node is RenderedFileNode => node !== undefined);
	for (const node of generated) {
		if (
			!copyNodes.some(
				(candidate) => candidate.relativePath === node.relativePath,
			)
		) {
			copyNodes.push({ relativePath: node.relativePath, bytes: node.bytes });
		}
	}
	copyNodes.sort(compareRelativePath);

	const sourceDigest = digestSource(source.files);
	const renderedDigest = digestFiles(copyNodes);
	return {
		mode: options.mode,
		sourceShape: source.shape,
		canonicalSource: source.canonicalSource,
		sourceDigest,
		renderedDigest,
		baselineDigest:
			options.mode === "copy"
				? renderedDigest
				: options.asset.generatedInputs
					? digestWrapper(authoredLinks, generated)
					: sha256(
							Buffer.from(
								JSON.stringify([
									source.canonicalSource,
									source.shape === "directory" ? "directory" : "flat-skill",
								]),
							),
						),
		copyNodes,
		directLinkShape:
			options.mode === "link" && !options.asset.generatedInputs
				? source.shape === "directory"
					? "directory"
					: "flat-skill"
				: undefined,
		authoredLinks: authoredLinks.sort(compareRelativePath),
		generatedNodes: generated,
	};
}

function resolveLinkShape(
	asset: HarnessAsset,
	sourceShape: "directory" | "file",
): HarnessLinkShape {
	if (asset.generatedInputs) return "generated-wrapper";
	return sourceShape === "directory" ? "directory" : "flat-skill";
}

function validateLinkShape(
	asset: HarnessAsset,
	target: ResolvedHarnessAssetTarget,
	mode: SyncMode,
	linkShape: HarnessLinkShape,
): void {
	if (mode !== "link" || target.supportedLinkShapes.includes(linkShape)) return;
	const registered =
		target.supportedLinkShapes.length > 0
			? target.supportedLinkShapes.join(", ")
			: "none";
	throw new Error(
		`Asset "${asset.assetId}" resolves link shape "${linkShape}", which harness target "${target.targetId}" does not register; registered link shapes: ${registered}. Use copy mode or select a target that registers this link shape.`,
	);
}

export async function writePreparedTarget(options: {
	readonly targetPath: string;
	readonly prepared: PreparedHarnessMaterialization;
}): Promise<void> {
	await rm(options.targetPath, { recursive: true, force: true });
	await mkdir(join(options.targetPath, ".."), { recursive: true });
	const { prepared } = options;
	if (prepared.mode === "copy") {
		await writeCopyTarget(options.targetPath, prepared);
		return;
	}
	if (prepared.generatedNodes.length > 0) {
		await writeGeneratedWrapper(options.targetPath, prepared);
		return;
	}
	if (prepared.directLinkShape === "directory") {
		await symlink(prepared.canonicalSource, options.targetPath, "dir");
		return;
	}
	await mkdir(options.targetPath, { recursive: true });
	await symlink(
		prepared.canonicalSource,
		join(options.targetPath, "SKILL.md"),
		"file",
	);
}

export function digestRenderedFiles(
	nodes: readonly RenderedFileNode[],
): string {
	return digestFiles(nodes);
}

function frontmatterEndOffset(source: Buffer): number {
	const firstLineEnd = findLineEnd(source, 0);
	if (firstLineEnd.contentEnd !== 3) return 0;
	if (!source.subarray(0, 3).equals(Buffer.from("---"))) return 0;
	if (firstLineEnd.nextOffset === firstLineEnd.contentEnd) return 0;

	let offset = firstLineEnd.nextOffset;
	while (offset <= source.length) {
		const line = findLineEnd(source, offset);
		if (
			line.contentEnd - offset === 3 &&
			source.subarray(offset, line.contentEnd).equals(Buffer.from("---"))
		) {
			return line.nextOffset;
		}
		if (line.nextOffset === offset || line.nextOffset >= source.length) break;
		offset = line.nextOffset;
	}
	return 0;
}

function findLineEnd(
	source: Buffer,
	start: number,
): { contentEnd: number; nextOffset: number } {
	const lf = source.indexOf(0x0a, start);
	if (lf === -1) {
		return { contentEnd: source.length, nextOffset: source.length };
	}
	const contentEnd = lf > start && source[lf - 1] === 0x0d ? lf - 1 : lf;
	return { contentEnd, nextOffset: lf + 1 };
}

function validateTargetShape(
	asset: HarnessAsset,
	target: ResolvedHarnessAssetTarget,
	mode: SyncMode,
): void {
	if (asset.assetId !== target.assetId || asset.kind !== target.kind) {
		throw new Error(
			`Target descriptor does not match asset "${asset.assetId}" and kind "${asset.kind}".`,
		);
	}
	if (!target.supportedModes.includes(mode)) {
		throw new Error(
			`Asset "${asset.assetId}" does not support requested mode "${mode}"; supported modes: ${target.supportedModes.join(", ")}.`,
		);
	}
	assertContainedPath(
		target.ownerRoot,
		target.targetDirectory,
		"target directory",
	);
	assertContainedPath(target.ownerRoot, target.targetPath, "target path");
}

async function readRegisteredSource(
	projectRoot: string,
	asset: HarnessAsset,
): Promise<{
	readonly shape: "directory" | "file";
	readonly canonicalSource: string;
	readonly files: readonly SourceFileNode[];
}> {
	assertLocalPath(asset.sourceRoot, "source root");
	assertLocalPath(asset.sourcePath, "source path");
	if (!isAbsolute(asset.sourceRoot)) {
		throw new Error(
			`Asset "${asset.assetId}" source root must be an absolute local path.`,
		);
	}
	if (isAbsolute(asset.sourcePath)) {
		throw new Error(
			`Asset "${asset.assetId}" source path must be relative to its registered source root.`,
		);
	}
	const declaredSource = resolve(asset.sourceRoot, asset.sourcePath);
	assertContainedPath(asset.sourceRoot, declaredSource, "source path");

	let canonicalRoot: string;
	let canonicalSource: string;
	try {
		canonicalRoot = await realpath(asset.sourceRoot);
		canonicalSource = await realpath(declaredSource);
	} catch (error) {
		throw new Error(
			`Asset "${asset.assetId}" has a missing or broken registered local source: ${declaredSource}.`,
			{ cause: error },
		);
	}
	assertContainedPath(canonicalRoot, canonicalSource, "canonical source");
	if (asset.ownership.kind === "project") {
		const canonicalProject = await realpath(projectRoot);
		assertContainedPath(canonicalProject, canonicalSource, "project source");
	}

	const stats = await lstat(canonicalSource);
	if (!stats.isDirectory() && !stats.isFile()) {
		throw new Error(
			`Asset "${asset.assetId}" source must resolve to a regular file or directory.`,
		);
	}
	const shape = stats.isDirectory() ? "directory" : "file";
	const files =
		shape === "directory"
			? await readSourceDirectory(canonicalRoot, canonicalSource)
			: [
					{
						relativePath: asset.kind === "skill" ? "SKILL.md" : "",
						canonicalSource,
						bytes: await readFile(canonicalSource),
					},
				];
	return { shape, canonicalSource, files };
}

async function readSourceDirectory(
	canonicalRoot: string,
	canonicalSource: string,
): Promise<readonly SourceFileNode[]> {
	const files: SourceFileNode[] = [];
	const visited = new Set<string>();
	async function walk(directory: string, prefix: string): Promise<void> {
		const canonicalDirectory = await resolveSafeDescendant(
			canonicalRoot,
			directory,
		);
		if (visited.has(canonicalDirectory)) {
			throw new Error(
				`Registered source contains a recursive symlink: ${directory}.`,
			);
		}
		visited.add(canonicalDirectory);
		const entries = await readdir(directory, { withFileTypes: true });
		entries.sort((left, right) => left.name.localeCompare(right.name));
		for (const entry of entries) {
			const path = join(directory, entry.name);
			const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
			const canonicalPath = await resolveSafeDescendant(canonicalRoot, path);
			const stats = await lstat(canonicalPath);
			if (stats.isDirectory()) {
				await walk(path, relativePath);
				continue;
			}
			if (!stats.isFile()) {
				throw new Error(
					`Registered source node must resolve to a regular file: ${path}.`,
				);
			}
			files.push({
				relativePath,
				canonicalSource: canonicalPath,
				bytes: await readFile(canonicalPath),
			});
		}
		visited.delete(canonicalDirectory);
	}
	await walk(canonicalSource, "");
	return files.sort(compareRelativePath);
}

async function resolveSafeDescendant(
	canonicalRoot: string,
	path: string,
): Promise<string> {
	let canonicalPath: string;
	try {
		canonicalPath = await realpath(path);
	} catch (error) {
		throw new Error(`Registered source contains a broken symlink: ${path}.`, {
			cause: error,
		});
	}
	assertContainedPath(canonicalRoot, canonicalPath, "source symlink target");
	return canonicalPath;
}

function prepareGeneratedNodes(
	nodes: readonly GeneratedHarnessNode[],
): PreparedGeneratedNode[] {
	const seen = new Set<string>();
	const prepared = nodes.map((node) => {
		validateRelativeNodePath(node.relativePath, "generated node");
		if (seen.has(node.relativePath)) {
			throw new Error(`Duplicate generated node path: ${node.relativePath}.`);
		}
		seen.add(node.relativePath);
		const bytes = Buffer.from(node.renderedBytes);
		return {
			relativePath: node.relativePath,
			inputDigest: sha256(node.inputBytes),
			renderedDigest: sha256(bytes),
			targetDigest: sha256(bytes),
			bytes,
		};
	});
	return prepared.sort(compareRelativePath);
}

function validateGeneratedShape(
	asset: HarnessAsset,
	source: {
		readonly shape: "directory" | "file";
		readonly files: readonly SourceFileNode[];
	},
	generated: readonly PreparedGeneratedNode[],
): void {
	if (!asset.generatedInputs && generated.length > 0) {
		throw new Error(
			`Asset "${asset.assetId}" does not declare generated inputs but generated nodes were supplied.`,
		);
	}
	if (asset.generatedInputs && source.shape !== "directory") {
		throw new Error(
			`Generated-wrapper asset "${asset.assetId}" must use a directory source.`,
		);
	}
	if (asset.generatedInputs && generated.length === 0) {
		throw new Error(
			`Generated-wrapper asset "${asset.assetId}" requires at least one generated node.`,
		);
	}
	const sourcePaths = new Set(source.files.map((node) => node.relativePath));
	for (const node of generated) {
		for (const sourcePath of sourcePaths) {
			if (
				sourcePath !== node.relativePath &&
				(sourcePath.startsWith(`${node.relativePath}/`) ||
					node.relativePath.startsWith(`${sourcePath}/`))
			) {
				throw new Error(
					`Generated node "${node.relativePath}" conflicts with authored node "${sourcePath}".`,
				);
			}
		}
	}
}

function shouldAddMarker(
	asset: HarnessAsset,
	shape: "directory" | "file",
	relativePath: string,
): boolean {
	return asset.kind === "command"
		? shape === "file" && relativePath === ""
		: relativePath === "SKILL.md";
}

async function writeCopyTarget(
	targetPath: string,
	prepared: PreparedHarnessMaterialization,
): Promise<void> {
	if (
		prepared.sourceShape === "file" &&
		prepared.copyNodes[0]?.relativePath === ""
	) {
		await writeFile(targetPath, prepared.copyNodes[0].bytes);
		return;
	}
	await mkdir(targetPath, { recursive: true });
	for (const node of prepared.copyNodes) {
		const output = join(targetPath, ...node.relativePath.split("/"));
		await mkdir(join(output, ".."), { recursive: true });
		await writeFile(output, node.bytes);
	}
}

async function writeGeneratedWrapper(
	targetPath: string,
	prepared: PreparedHarnessMaterialization,
): Promise<void> {
	await mkdir(targetPath, { recursive: true });
	for (const link of prepared.authoredLinks) {
		const output = join(targetPath, ...link.relativePath.split("/"));
		await mkdir(join(output, ".."), { recursive: true });
		await symlink(link.expectedCanonicalSource, output, "file");
	}
	for (const node of prepared.generatedNodes) {
		const output = join(targetPath, ...node.relativePath.split("/"));
		await mkdir(join(output, ".."), { recursive: true });
		await writeFile(output, node.bytes);
	}
}

function digestSource(nodes: readonly SourceFileNode[]): string {
	if (nodes.length === 1) return sha256(nodes[0]?.bytes ?? Buffer.alloc(0));
	return sha256(
		Buffer.from(
			nodes
				.map((node) => `${node.relativePath}\0${sha256(node.bytes)}\n`)
				.join(""),
		),
	);
}

function digestFiles(nodes: readonly RenderedFileNode[]): string {
	if (nodes.length === 1) return sha256(nodes[0]?.bytes ?? Buffer.alloc(0));
	return sha256(
		Buffer.from(
			nodes
				.map((node) => `${node.relativePath}\0${sha256(node.bytes)}\n`)
				.join(""),
		),
	);
}

function digestWrapper(
	authoredLinks: readonly HarnessAuthoredLink[],
	generatedNodes: readonly PreparedGeneratedNode[],
): string {
	return sha256(
		Buffer.from(
			JSON.stringify({
				authoredLinks,
				generatedNodes: generatedNodes.map(
					({ relativePath, inputDigest, renderedDigest, targetDigest }) => ({
						relativePath,
						inputDigest,
						renderedDigest,
						targetDigest,
					}),
				),
			}),
		),
	);
}

function assertLocalPath(value: string, label: string): void {
	if (/^(?:[a-z][a-z0-9+.-]*:|git@)/i.test(value)) {
		throw new Error(
			`${label} must be a registered local filesystem path: ${value}.`,
		);
	}
}

function assertContainedPath(
	root: string,
	candidate: string,
	label: string,
): void {
	const relativePath = relative(resolve(root), resolve(candidate));
	if (
		relativePath === "" ||
		(!relativePath.startsWith(`..${sep}`) &&
			relativePath !== ".." &&
			!isAbsolute(relativePath))
	) {
		return;
	}
	throw new Error(`${label} escapes its registered root: ${candidate}.`);
}

function validateRelativeNodePath(path: string, label: string): void {
	if (
		path.length === 0 ||
		isAbsolute(path) ||
		path.includes("\\") ||
		path.split("/").some((part) => part === "" || part === "." || part === "..")
	) {
		throw new Error(
			`${label} path must be a safe relative POSIX path: ${path}.`,
		);
	}
}

function compareRelativePath(
	left: { readonly relativePath: string },
	right: { readonly relativePath: string },
): number {
	return left.relativePath.localeCompare(right.relativePath);
}
